<?php

/**
 * Implements hook_feeds_plugins().
 */
function csv2fields_feeds_plugins() {
  $info = array();
  $info['FeedsEntityStructureProcessor'] = array(
    'name' => 'Entity Structure Processor',
    'description' => 'Scaffolds entity structure.',
    'handler' => array(
      'parent' => 'FeedsProcessor', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class' => 'FeedsEntityStructureProcessor',
      'file' => 'plugins/FeedsEntityStructureProcessor.inc',
      'path' => drupal_get_path('module', 'csv2fields'),
    ),
  );
  return $info;
}
